Feature: Detect masterkey change
cryptomator/ios pull request #161
Opened 2022-02-01 13:21 UTC by phil1995

Refreshes the cached vault during each manual unlock and thus fixes #142.

If there is currently no internet connection, the already cached vault is used.

It may now happen that the password stored in the keychain for the biometric unlock is no longer correct. In this case, a special error message is displayed to the user, the old password is removed from the keychain and the enable biometric unlock switch is already set to on for the next unlock.

At the same time, another customized error message was introduced if the user cancels the biometric unlock.

Note: The customized authentication errors are now possible in the FileProviderExtension, because we now use undocumented FileProviderErrorKeys (googling these error keys currently does not even lead to a single search result).

2022-02-01 13:58 UTC, tobihagemann requested changes

2022-02-01 13:58 UTC, tobihagemann commented on CryptomatorCommon/Sources/CryptomatorCommonCore/Manager/VaultDBCache.swift
> +	}
This seems unused.

2022-02-01 13:58 UTC, tobihagemann commented on CryptomatorCommon/Sources/CryptomatorCommonCore/Manager/VaultDBManager.swift
> +		let cachedVault = CachedVault(vaultUID: vaultUID, masterkeyFileData: masterkeyFileData, vaultConfigToken: vaultConfigToken, lastUpToDateCheck: Date(), masterkeyFileLastModifiedDate: nil, vaultConfi
Should these dates really be set to `nil`? Wouldn't this cause the cache to be invalidated with the next unlock?

2022-02-02 14:23 UTC, tobihagemann requested changes
I did the following test with a vault "On My iPhone" (simulator), which I copied from my Mac:

1. Unlock vault and then lock vault (just to make sure that the cached vault is up-to-date)
2. Change password of that vault on my Mac
3. Delete `masterkey.cryptomator` on iOS and add the new `masterkey.cryptomator` from step 2 (basically, replace the masterkey file)
4. Unlock vault with new password

At first, the unlock is not successful because of "wrong password" (shaking screen). But if I press "Unlock" again (without changing anything, still using the new password), the unlock is successful.

It seems to me that the cached vault is not invalidated soon enough.

2022-02-02 18:42 UTC, phil1995 commented
> I did the following test with a vault "On My iPhone" (simulator), which I copied from my Mac:
> 
> 1. Unlock vault and then lock vault (just to make sure that the cached vault is up-to-date)
> 2. Change password of that vault on my Mac
> 3. Delete `masterkey.cryptomator` on iOS and add the new `masterkey.cryptomator` from step 2 (basically, replace the masterkey file)
> 4. Unlock vault with new password
> 
> At first, the unlock is not successful because of "wrong password" (shaking screen). But if I press "Unlock" again (without changing anything, still using the new password), the unlock is successful.
> 
> It seems to me that the cached vault is not invalidated soon enough.

Indeed the vault cache was refreshed / updated too late, because it is already accessed in the `FileProviderExtensionUI` (to derive the KEK) and the cache was not refreshed until the derived KEK was already passed via XPC.

Should be fixed now - the vault cache is now already updated in the `FileProviderExtensionUI` (in the `UnlockVaultViewModel`) so that the KEK is actually derived from the current version of the masterkey file.

2022-02-03 13:48 UTC, tobihagemann requested changes
Since errors during an unlock due to remote changes is now a thing, we should use the `LocalizedCloudProviderDecorator` so that the error messages are more meaningful. :smile:

I noticed that while testing a vault, where I removed the masterkey file.

2022-02-07 12:39 UTC, tobihagemann approved these changes

2022-02-07 12:39 UTC, merged